# [1]

#### (i) ¿Cómo representarías a una partícula en 1D con posición, velocidad y masa en Julia?

Lo representaría con un vector, donde la primer entrada fuera la posición, la segunda la velocidad y la tercera la masa

In [4]:
x=[0.0,2.0,100.0] #partícula en pos=0, con vel=2 y masa=100

3-element Array{Float64,1}:
   0.0
   2.0
 100.0

#### (ii) ¿Cómo moverías la partícula en un paso δt?

x+[δpos,δvel,δmas]

#### (iii) ¿Si necesitas otra partícula con las mismas propiedades, qué harías?

In [5]:
y=similar(x)

3-element Array{Float64,1}:
 8.67726e-317
 8.67571e-317
 8.67571e-317

#### (iv) Para N tales partículas, ¿qué podrías hacer?

In [6]:
#podría hacer un arreglo en donde la primer entrada sea el número de particula y la segunda la propiedad
N=5
z=zeros(N,length(x)) 

5x3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [7]:
#O mejor aún podría crear un vector cuyas entradas fueran del tipo arreglo
z=Array{Float64,1}[]

0-element Array{Array{Float64,1},1}

In [8]:
#Y agregar las N partículas:
N=5
for i=1:N
    push!(z,similar(x))
end
z

5-element Array{Array{Float64,1},1}:
 [7.7275e-316,8.67515e-317,8.67565e-317] 
 [7.59147e-316,3.0735e-316,3.0735e-316]  
 [9.43519e-317,8.67039e-317,8.67565e-317]
 [3.34865e-316,3.34864e-316,3.34864e-316]
 [9.43519e-317,8.67039e-317,8.67565e-317]

# [2]

#### Define un tipo que se llama `Particula`, que tiene variables para la posición, velocidad y masa en una dimensión.

In [9]:
type Particula
    pos::Float64
    vel::Float64
    masa::Float64
end

In [10]:
Particula(1,2,33,3)

LoadError: `Particula` has no method matching Particula(::Int64, ::Int64, ::Int64, ::Int64)
while loading In[10], in expression starting on line 1

# [3]

#### Experimenta para ver cómo crear un objeto de tipo `Particula`. [Pista: piensa en funciones]

Lo siguiente es para conocer un poco `type`

In [28]:
methods(Particula)

# 2 methods for generic function "Particula":
Particula(pos::Float64,vel::Float64,masa::Float64)
Particula(pos,vel,masa)

In [11]:
part1=Particula(0.0,2.0,100.0)

Particula(0.0,2.0,100.0)

In [12]:
names(part1)

3-element Array{Symbol,1}:
 :pos 
 :vel 
 :masa

In [13]:
typeof(part1)

Particula (constructor with 2 methods)

In [14]:
println(part1.pos)
println(part1.vel)
println(part1.masa)

0.0
2.0
100.0


In [15]:
part1.pos=10*part1.vel
println(part1.pos)
println(part1.vel)
println(part1.masa)

20.0
2.0
100.0


# [4]

#### ¿Cómo podemos definir una función `mover` que mueve la partícula en un paso de tiempo `δt`? [Pista: Para especificar que un objeto t es de tipo `MiTipo`, usamos la sintaxis `t::MiTipo`.]

In [16]:
function mover!(x::Particula,δt::Float64) #el ! es porque cambia el valor del argumento (consejo julia)
    x.pos+=δt*x.vel #estoy pensando que la partícula está libre de aceleración.
    x
end

mover! (generic function with 1 method)

In [17]:
println(part1)
mover!(part1,10.0)

Particula(20.0,2.0,100.0)


Particula(40.0,2.0,100.0)

# [5]

El que sigue era la primera opción que yo hice, pero me dijeron que era mejor hacer lo que pongo después

type Gas #El objeto gas representa N partículas, de modo que 'pos', 'vel' y 'masa' son vectores de tamaño N
            #en los cuales misma posición indica misma partícula
    pos::Array{Float64,1}
    vel::Array{Float64,1}
    masa::Array{Float64,1}
    
    #la parte siguiente es para asegurar que el tamaño de 'pos', 'vel' y 'masa' sea el mismo.
    #La idea la saqué de internet en donde usan el 'ternary operator', en este caso podría escribirse así
    #Gas(pos,vel,masa)= (length(pos)!=length(vel) || length(vel)!=length(masa) ?
    #                    error("Deben ser tres arreglos del mismo tamaño") : new(pos,vel,masa))
    Gas(pos,vel,masa)=      
    if length(pos)!=length(vel) || length(vel)!=length(masa)
        error("Deben ser tres arreglos del mismo tamaño")
    else
        new(pos,vel,masa)
    end
end    

In [18]:
type Gas #El objeto gas representa N partículas, de modo que la primer entrada es el número de partículas y 
            #la segunda entrada es un vector cuyas entradas son elementos tipo Particula
    n::Int64
    particulas::Vector{Particula}
    
    #la parte siguiente es para asegurar que el n coincide con el tamaño del vector
    #La idea la saqué de internet en donde usan el 'ternary operator' a ? b : c (if a then b, else c)
    Gas(n::Int64,particulas::Vector{Particula})=
    (length(particulas)!=n ? error("n es el número de partículas") : new(n::Int64,particulas::Vector{Particula}))
end    

In [19]:
partgas=Gas(3,[part1,part1])

LoadError: n es el número de partículas
while loading In[19], in expression starting on line 1

In [20]:
part1=Particula(0.0,2.0,100.0)
part2=Particula(10.0,1.0,100.0)
partgas=Gas(2,[part1,part2])

Gas(2,[Particula(0.0,2.0,100.0),Particula(10.0,1.0,100.0)])

In [21]:
#ahora defino Gas para unicamente un arreglo
Gas(particulas::Vector{Particula})=Gas(length(particulas),particulas)

Gas (constructor with 2 methods)

In [22]:
methods(Gas)

# 2 methods for generic function "Gas":
Gas(n::Int64,particulas::Array{Particula,1}) at In[18]:8
Gas(particulas::Array{Particula,1}) at In[21]:2

In [23]:
function mover!(x::Gas,δt::Float64) #el ! es porque cambia el valor del argumento (consejo julia)
    for n=1:x.n #estoy pensando que las partículas están libres de aceleración.
        mover!(x.particulas[n],δt)
    end
    x
end

mover! (generic function with 2 methods)

In [24]:
methods(mover!)

# 2 methods for generic function "mover!":
mover!(x::Particula,δt::Float64) at In[16]:2
mover!(x::Gas,δt::Float64) at In[23]:2

In [25]:
println(partgas)
mover!(partgas,10.0)

Gas(2,[Particula(0.0,2.0,100.0),Particula(10.0,1.0,100.0)])


Gas(2,[Particula(20.0,2.0,100.0),Particula(20.0,1.0,100.0)])

In [26]:
partgas

Gas(2,[Particula(20.0,2.0,100.0),Particula(20.0,1.0,100.0)])

# [6]

#### (i)

In [37]:
type Barra
    barra1::Float64
    barra2::Float64
end

Barra(barra1)= Barra(barra1,1.0)

Barra (constructor with 3 methods)

In [38]:
function +(x::Barra,y::Barra) #defino la suma entre barras
    z=Barra(0.0,0.0)
    z.barra1=x.barra1+y.barra1
    z.barra2=x.barra2+y.barra2
    z
end

function +(x::Number,y::Barra) #defino la suma número + barra
    Barra(x,0.0)+y
end
function +(y::Barra,x::Number) #defino la suma barra + número
    x+y
end

function -(x::Barra,y::Barra) #defino la resta
    z=Barra(0.0,0.0)
    z.barra1=x.barra1-y.barra1
    z.barra2=x.barra2-y.barra2
    z
end

function -(x::Number,y::Barra) #defino la resta número - barra
    Barra(x,0.0)-y
end
function -(y::Barra,x::Number) #defino la suma barra - número
    y-Barra(x,0.0)
end

function *(x::Barra,y::Barra) #defino producto entre barras
    z=Barra(0.0,0.0)
    z.barra1=x.barra1*y.barra1
    z.barra2=x.barra1*y.barra2+x.barra2*y.barra1
    z
end

function *(x::Number,y::Barra) #defino producto barra por número
    Barra(x,0.0)*y
end
function *(y::Barra,x::Number) #defino producto barra por número
    x*y
end

function /(x::Barra,y::Barra) #defino división
    z=Barra(0.0,0.0)
    z.barra1=x.barra1/y.barra1
    z.barra2=(x.barra2*y.barra1-x.barra1*y.barra2)/y.barra1^2
    z
end

function ^(x::Barra,y::Float64) #defino potencia para flotantes
    z=Barra(0.0,0.0)
    z.barra1=x.barra1^y
    z.barra2=y*x.barra1^(y-1)*x.barra2
    z
end
function ^(x::Barra,y::Int64) #defino potencia para enteros
    x^float64(y)
end
function ^(x::Barra,y::Rational{Int64}) #defino potencia para racionales
    x^float64(y)
end
;

In [39]:
a=Barra(1,1)
b=Barra(2,3)
println(a+b)
println(a-b)
println(a*b)
println(a/b)
println(b^2)

Barra(3.0,4.0)
Barra(-1.0,-2.0)
Barra(2.0,5.0)
Barra(0.5,-0.25)
Barra(4.0,12.0)


#### (ii)

#### Define un polinomio $p(x)$ cuya variable independiente es $x$.

In [27]:
function polinomio(x)
    (x^4) + 2*(x^3) - 2*(x^2) + 2*(x) - 3
end

polinomio (generic function with 1 method)

#### Evalúa el polinomio en $\bar x$ (variable independiente $x$), en $x0=0$.

In [28]:
x=0.0
polinomio(Barra(x))

Barra(-3.0,2.0)

#### ¿Qué interpretación tiene el valor obtenido para $d_x$?

In [29]:
#me parece que el valor obtenido para d_x es la derivada del polinomio evaluada en x
function polinomio_der(x)
    4*(x^3) + 6*(x^2) - 4*(x) + 2
end

polinomio_der (generic function with 1 method)

In [30]:
x=0.0
println(polinomio_der(x))
println(polinomio(Barra(x)).barra2)

2.0
2.0


#### ¿Y si en lugar de un polinomio utilizas un cociente de polinomios $r(\bar x)=p(\bar x)/q(\bar x)$?

Primero lo voy a a hacer por separado:

In [31]:
function pol_q(x)
    x+3
end
x=0.0
polinomio(Barra(x))/pol_q(Barra(x))

Barra(-1.0,1.0)

Ahora lo voy a hacer con una función:

In [32]:
function pol_r(x)
    ((x^4) + 2*(x^3) - 2*(x^2) + 2*(x) - 3)/(x+3)
end
x=0.0
pol_r(Barra(x))

Barra(-1.0,1.0)

Por lo tanto es consistente, notemos además que el primer polinomio se puede escribir como:

\begin{equation}
    p(x)=x^4 + 2x^3 - 2x^2 + 2x - 3 = (x^2 +1)(x+3 ) (x -1) 
\end{equation}

Por lo que el cociente de 
\begin{equation}
r(x)=p(x)/q(x) = (x^2 +1)(x -1)= x^3-x^2+x-1
\end{equation}

De modo que su derivada es 
\begin{equation}
r'(x)=3x^2-2x+1
\end{equation}

In [33]:
function pol_r_der(x)
    3*(x^2) - 2*(x) + 1
end;

In [34]:
x=1.0
println(pol_r(Barra(x)).barra2)
println(pol_r_der(x))

2.0
2.0


Por lo que para el cociente de polinomios se sigue cumpliendo que $d_x$ es la derivada evaluada en $x$

#### (iii)

#### Pensando en la interpretación que le diste a $d_x$, cómo definirías la acción sobre $\bar{x}$ de las siguientes funciones:

- exp($\bar x$)
- log($\bar x$)
- sin($\bar x$)
- cos($\bar x$)
- tan($\bar x$)

In [40]:
import Base.exp #no se porqué pero para agregar otro método a estas funciones tenía que importarlas
import Base.log
import Base.sin
import Base.cos
import Base.tan


function exp(x::Barra)
    z=Barra(0.0,0.0)
    z.barra1=exp(x.barra1)
    z.barra2=exp(x.barra1)*x.barra2 #la derivada de exp es ella misma
    z
end

function log(x::Barra)
    z=Barra(0.0,0.0)
    z.barra1=log(x.barra1)
    z.barra2=(1/(x.barra1))*x.barra2 #la derivada de log(x) es 1/x
    z
end

function sin(x::Barra)
    z=Barra(0.0,0.0)
    z.barra1=sin(x.barra1)
    z.barra2=cos(x.barra1)*x.barra2 #la derivada de sin(x) es cos(x)
    z
end

function cos(x::Barra)
    z=Barra(0.0,0.0)
    z.barra1=cos(x.barra1)
    z.barra2=-sin(x.barra1)*x.barra2 #la derivada de cos(x) es -sin(x)
    z
end

function tan(x::Barra)
    z=Barra(0.0,0.0)
    z.barra1=tan(x.barra1)
    z.barra2=(1/(cos(x.barra1))^2)*x.barra2 #la derivada de tan(x) es 1/(cos(x))^2
    z
end;

In [41]:
x=Barra(1)
println(exp(x))
println(log(x))
println(sin(x))
println(cos(x))
println(tan(x))

Barra(2.718281828459045,2.718281828459045)
Barra(0.0,1.0)
Barra(0.8414709848078965,0.5403023058681398)
Barra(0.5403023058681398,-0.8414709848078965)
Barra(1.5574077246549023,3.425518820814759)


In [42]:
x = Barra(2.0)

Barra(2.0,1.0)

In [43]:
sin(x^2 + 3*x)

Barra(-0.5440211108893698,-5.873500703535167)

In [44]:
sin(sin(x^2 + 3x))

Barra(-0.5175807674647733,-5.025568985012155)

#### (iv)

#### ¿Cómo podemos definir las cosas en Julia de tal manera que $\bar v + c$, y las demás posibles operaciones entre una variable compósita y un flotante $c$, tengan sentido?

Lo que hice al definir las operaciones más arriba fue convertir $c$ en $\bar c = (c,0)$ y luego hacer las operaciones

# [7]

#### En el resto del curso, trataremos con aritmética de intervalos. En este nuevo tipo de aritmética, ocupamos intervalos $[a,b]$ de la recta real, que es el conjunto  \begin{equation}     [a,b]:= \{ x:a\leq x \leq b \} \end{equation}

#### (i) Define un tipo composito para representar un intervalo de dos números reales.

In [20]:
type Interval
    a::Float64
    b::Float64
    
    Interval(a::Float64,b::Float64) = ( a>=b ? new(b,a) : new(a,b))
end

Interval(a,b)=Interval(float64(a),float64(a))

Interval (constructor with 2 methods)

In [21]:
methods(Interval)

# 2 methods for generic function "Interval":
Interval(a::Float64,b::Float64) at In[20]:5
Interval(a,b) at In[20]:8

In [22]:
Interval(11,2)

Interval(11.0,11.0)

In [23]:
Interval("0.1",1)

Interval(0.1,0.1)

#### (ii) ¿Cómo podríamos tener operaciones sensatas sobre los intervalos? La idea básica es que el resultado de la operación sobre dos intervalos contenga los valores posibles resultantes de operar con los miembros de los dos intervalos respectivos.

Solo tenemos que operar con los extremos de los intervalos, teniendo cuidado de algunos casos particulares, como por ejemplo si el intervalo contiene cero no podemos dividir entre ese intervalo. 

#### (iii) Implementa estas operaciones, sin tomar en cuenta cuestiones de redondeo.

In [39]:
function +(x::Interval,y::Interval) #defino suma entre intervalos
    z=Interval(0.0,1.0)
    z.a=x.a+y.a
    z.b=x.b+y.b
    z
end

function +(x::Number,y::Interval) #defino suma entre números e intervalos
    z=Interval(0.0,1.0)
    z.a=x+y.a
    z.b=x+y.b
    z
end
function +(y::Interval,x::Number) 
    x+y
end
    
function -(x::Interval,y::Interval) #defino suma entre intervalos
    z=Interval(0.0,1.0)
    z.a=x.a-y.b
    z.b=x.b-y.a
    z
end

function -(x::Number,y::Interval) #defino resta entre números e intervalos
    z=Interval(0.0,1.0)
    z.a=x-y.b
    z.b=x-y.a
    z
end
function -(y::Interval,x::Number) 
    z=Interval(0.0,1.0)
    z.a=y.a-x
    z.b=y.b-x
    z
end

function *(x::Interval,y::Interval) #defino producto entre intervalos
    z=Interval(0.0,1.0)
    z.a=min(x.a*y.a,x.a*y.b,x.b*y.a,x.b*y.b)
    z.b=max(x.a*y.a,x.a*y.b,x.b*y.a,x.b*y.b)
    z
end

function *(x::Number,y::Interval) #defino producto entre número e intervalo
    z=Interval(0.0,1.0)
    z.a=min(x*y.a,x*y.b)
    z.b=max(x*y.a,x*y.b)
    z
end
function *(y::Interval,x::Number)
    x*y
end

function /(x::Interval,y::Interval) #defino división entre intervalos
    if y.a<0.0&&y.b>0
        error("el intervalo divisor no puede contener al cero")
    else
        z=Interval(0.0,1.0)
        z.a=min(x.a/y.a,x.a/y.b,x.b/y.a,x.b/y.b)
        z.b=max(x.a/y.a,x.a/y.b,x.b/y.a,x.b/y.b)
        z
    end
end

function /(x::Number,y::Interval) #defino división entre número e intervalo
    if y.a<0.0&&y.b>0
        error("el intervalo divisor no puede contener al cero")
    else
        z=Interval(0.0,1.0)
        z.a=min(x/y.a,x/y.b)
        z.b=max(x/y.a,x/y.b)
        z
    end
end
function /(y::Interval,x::Number)
    if float64(x)==0.0
        error("no puedo dividir un intervalo entre cero")
    else
        z=Interval(0.0,1.0)
        z.a=min(y.a/x,y.b/x)
        z.b=max(y.a/x,y.b/x)
        z
    end
end

function ^(y::Interval,x::Integer) #defino potencia intervalo^entero
    z=Interval(0.0,1.0)
    if y.a<0.0&&y.b>0&&x<0
        error("el intervalo no puede contener al cero con exponentes negativos")
    elseif y.a<0.0&&y.b>0&&x!=0
        z.a=min(0,y.a^x,y.b^x)
    else
        z.a=min(y.a^x,y.b^x)
    end
    z.b=max(y.a^x,y.b^x)
    z
end
        

^ (generic function with 49 methods)

In [40]:
a=Interval(-1,3)
b=Interval(12,13)
c=4
println("a+b=",a+b)
println("c+a=",c+a)
println("b-a=",b-a)
println("a-c=",a-c)
println("a*b=",a*b)
println("a*c=",a*c)
println("a/b=",a/b)
println("a/c=",a/c)
println("a^2=",a^2)
println("b^-1=",b^-1)

a+b=Interval(11.0,16.0)
c+a=Interval(3.0,7.0)
b-a=Interval(9.0,14.0)
a-c=Interval(-5.0,-1.0)
a*b=Interval(-13.0,39.0)
a*c=Interval(-4.0,12.0)
a/b=Interval(-0.08333333333333333,0.25)
a/c=Interval(-0.25,0.75)
a^2=Interval(0.0,9.0)
b^-1=Interval(0.07692307692307693,0.08333333333333333)


#### (iv) ¿Cómo nos puede ayudar el redondeo? Impleméntalo.

Nos puede ayudar para asegurar que el número REAL se encuentra dentro del intervalo de Flotantes.

In [41]:
old=get_rounding(Float64)

function +(x::Interval,y::Interval) #defino suma entre intervalos
    z=Interval(0.0,1.0)
    set_rounding(Float64,RoundDown)
    z.a=x.a+y.a
    set_rounding(Float64,RoundUp)
    z.b=x.b+y.b
    z
end

function +(x::Number,y::Interval) #defino suma entre números e intervalos
    z=Interval(0.0,1.0)
    set_rounding(Float64,RoundDown)
    z.a=x+y.a
    set_rounding(Float64,RoundUp)
    z.b=x+y.b
    z
end
function +(y::Interval,x::Number) 
    x+y
end
    
function -(x::Interval,y::Interval) #defino suma entre intervalos
    z=Interval(0.0,1.0)
    set_rounding(Float64,RoundDown)
    z.a=x.a-y.b
    set_rounding(Float64,RoundUp)
    z.b=x.b-y.a
    z
end

function -(x::Number,y::Interval) #defino resta entre números e intervalos
    z=Interval(0.0,1.0)
    set_rounding(Float64,RoundDown)
    z.a=x-y.b
    set_rounding(Float64,RoundUp)
    z.b=x-y.a
    z
end
function -(y::Interval,x::Number) 
    z=Interval(0.0,1.0)
    set_rounding(Float64,RoundDown)
    z.a=y.a-x
    set_rounding(Float64,RoundUp)
    z.b=y.b-x
    z
end

function *(x::Interval,y::Interval) #defino producto entre intervalos
    z=Interval(0.0,1.0)
    set_rounding(Float64,RoundDown)
    z.a=min(x.a*y.a,x.a*y.b,x.b*y.a,x.b*y.b)
    set_rounding(Float64,RoundUp)
    z.b=max(x.a*y.a,x.a*y.b,x.b*y.a,x.b*y.b)
    z
end

function *(x::Number,y::Interval) #defino producto entre número e intervalo
    z=Interval(0.0,1.0)
    set_rounding(Float64,RoundDown)
    z.a=min(x*y.a,x*y.b)
    set_rounding(Float64,RoundUp)
    z.b=max(x*y.a,x*y.b)
    z
end
function *(y::Interval,x::Number)
    x*y
end

function /(x::Interval,y::Interval) #defino división entre intervalos
    if y.a<0.0&&y.b>0
        error("el intervalo divisor no puede contener al cero")
    else
        z=Interval(0.0,1.0)
        set_rounding(Float64,RoundDown)
        z.a=min(x.a/y.a,x.a/y.b,x.b/y.a,x.b/y.b)
        set_rounding(Float64,RoundUp)
        z.b=max(x.a/y.a,x.a/y.b,x.b/y.a,x.b/y.b)
        z
    end
end

function /(x::Number,y::Interval) #defino división entre número e intervalo
    if y.a<0.0&&y.b>0
        error("el intervalo divisor no puede contener al cero")
    else
        z=Interval(0.0,1.0)
        set_rounding(Float64,RoundDown)
        z.a=min(x/y.a,x/y.b)
        set_rounding(Float64,RoundUp)
        z.b=max(x/y.a,x/y.b)
        z
    end
end
function /(y::Interval,x::Number)
    if float64(x)==0.0
        error("no puedo dividir un intervalo entre cero")
    else
        z=Interval(0.0,1.0)
        set_rounding(Float64,RoundDown)
        z.a=min(y.a/x,y.b/x)
        set_rounding(Float64,RoundUp)
        z.b=max(y.a/x,y.b/x)
        z
    end
end

function ^(y::Interval,x::Integer) #defino potencia intervalo^entero
    z=Interval(0.0,1.0)
    set_rounding(Float64,RoundDown)
    if y.a<0.0&&y.b>0&&x<0
        error("el intervalo no puede contener al cero con exponentes negativos")
    elseif y.a<0.0&&y.b>0&&x!=0
        z.a=min(0,y.a^x,y.b^x)
    else
        z.a=min(y.a^x,y.b^x)
    end
    set_rounding(Float64,RoundUp)
    z.b=max(y.a^x,y.b^x)
    z
end

set_rounding(Float64,old);

In [42]:
a=Interval(-1,3)
b=Interval(12,13)
c=4
println("a+b=",a+b)
println("c+a=",c+a)
println("b-a=",b-a)
println("a-c=",a-c)
println("a*b=",a*b)
println("a*c=",a*c)
println("a/b=",a/b)
println("a/c=",a/c)
println("a^2=",a^2)
println("b^-1=",b^-1)

a+b=Interval(11.0,16.0)
c+a=Interval(3.0,7.0)
b-a=Interval(9.0,14.0)
a-c=Interval(-5.0,-1.0)
a*b=Interval(-13.0,39.0)
a*c=Interval(-4.0,12.0)
a/b=Interval(-0.08333333333333334,0.25)
a/c=Interval(-0.25,0.75)
a^2=Interval(0.0,9.0)
b^-1=Interval(0.07692307692307691,0.08333333333333334)
